name: rainbow-triangle-web
services:
  server:
    build:
      context: ../
      dockerfile: web/Dockerfile
    ports:
      - "8080:80"
    restart: unless-stopped

  cloudflare:
    image: cloudflare/cloudflared:2026.6.0
    volumes:
      - ./.cloudflare/${TUNNEL_ID:-default}.json:/home/nonroot/.cloudflared/credentials.json:ro
      - ./.cloudflare/cert.pem:/home/nonroot/.cloudflared/cert.pem:ro
      - ./.cloudflare/config.yml:/home/nonroot/.cloudflared/config.yml:ro
    restart: unless-stopped
    command: tunnel run app_tunnel
